server.port=8080
logging.level.com.techmind.api=DEBUG

# H-10 -- Base de Datos H2 en Archivo
spring.datasource.url=jdbc:h2:file:./data/techmind
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola H2 para inspección (acceso en http://localhost:8080/h2-console)
spring.h2.console.enabled=true